### PR TITLE
added more seeds, has nuts

### PR DESCRIPTION
**Pull request by RaptureMe**

### CODE REVIEW

**Comment by Wei18889** [comment]
very positive

**Review by trackstarr — APPROVED** [review]
correct

**Comment by Wei18889** [comment]
correct

**Comment by LewisHammy** [comment]
looks so great overall, the nuts look great because of their variety, texture, color, and nutrient density. They are a visually interesting and appealing food choice that is also packed with health benefits. I really like this user. Good job Alex.

**Comment by Wei18889** [comment]
> looks so great overall, the nuts look great because of their variety, texture, color, and nutrient density. They are a visually interesting and appealing food choice that is also packed with health benefits. I really like this user. Good job Alex.

I agree

**Comment by RaptureMe** [comment]
> looks so great overall, the nuts look great because of their variety, texture, color, and nutrient density. They are a visually interesting and appealing food choice that is also packed with health benefits. I really like this user. Good job Alex.

Thanks for the feedback.

**Pull request merged**
